name: QWERTZcore
version: '${version}'
main: app.qwertz.qwertzcore.QWERTZcore
api-version: '1.19'
load: STARTUP
authors: [ QWERTZ_EXE ]
description: All in one event core!
website: https://qwertz.app
softdepend: [LuckPerms, PowerRanks, WorldGuard, PlaceholderAPI]
commands:
  core:
    description: Displays information about QWERTZ Core
    aliases: [qwertzcore]
    usage: /<command>
  timer:
    description: Starts or cancels a countdown timer
    usage: /<command> <seconds|cancel>
    permission: qwertzcore.host.timer
  gmc:
    description: Set gamemode to creative
    usage: /<command>
    permission: qwertzcore.gamemode.creative
  gms:
    description: Set gamemode to survival
    usage: /<command>
    permission: qwertzcore.gamemode.survival
  gmsp:
    description: Set gamemode to spectator
    usage: /<command>
    permission: qwertzcore.gamemode.spectator
  gma:
    description: Set gamemode to adventure
    usage: /<command>
    permission: qwertzcore.gamemode.adventure
  gm:
    description: Set gamemode
    usage: /<command> <creative|survival|adventure|spectator>
    permission: qwertzcore.gamemode
  chatrevive:
    description: Start a chat revival game
    usage: /<command> <math|typer|guess> [max]
    permission: qwertzcore.host.revival
  revive:
    description: Revive a player
    usage: /<command> <player>
    permission: qwertzcore.host.revive
  unrevive:
    description: Mark a player as dead
    usage: /<command> <player>
    permission: qwertzcore.host.unrevive
  reviveall:
    description: Revive all players
    usage: /<command>
    permission: qwertzcore.host.reviveall
  unreviveall:
    description: Unrevive all players
    usage: /<command>
    permission: qwertzcore.host.unreviveall
  listalive:
    description: List all alive players
    usage: /<command>
    permission: qwertzcore.player.listalive
  listdead:
    description: List all dead players
    usage: /<command>
    permission: qwertzcore.player.listdead
  givedead:
    description: Give an item to all dead players
    usage: /<command> <item> [amount] [data]
    permission: qwertzcore.host.givedead
  givealive:
    description: Give an item to all alive players
    usage: /<command> <item> [amount] [data]
    permission: qwertzcore.host.givealive
  tpalive:
    description: Teleport all alive players to you
    usage: /<command>
    permission: qwertzcore.host.tpalive
  tpdead:
    description: Teleport all dead players to you
    usage: /<command>
    permission: qwertzcore.host.tpdead
  tpall:
    description: Teleport all players to you
    usage: /<command>
    permission: qwertzcore.host.tpall
  tphere:
    description: Teleport the selected player to you
    usage: /<command> <player>
    permission: qwertzcore.host.tphere
  vanish:
    description: Vanishes the player from the server
    usage: /vanish
    permission: qwertzcore.host.vanish
  unvanish:
    description: Unvanishes the player from the server
    usage: /unvanish
    permission: qwertzcore.host.unvanish
  config:
    description: Edit configuration values
    usage: /config <key> <value>
    permission: qwertzcore.config
  spawn:
    description: Teleport to spawn location
    usage: /spawn
    permission: qwertzcore.player.spawn
  clearalive:
    description: Clears the inventory of all alive players
    usage: /clearalive
    permission: qwertzcore.host.clearalive
  cleardead:
    description: Clears the inventory of all dead players
    usage: /cleardead
    permission: qwertzcore.host.cleardead
  revivelast:
    description: Revives all players who died in the last specified number of seconds
    usage: /revivelast [seconds]
    permission: qwertzcore.host.revivelast
  hide:
    description: Hide other players based on their status
    usage: /hide <host|staff|all|off>
    permission: qwertzcore.player.hide
  eventcountdown:
    description: Start a countdown for the event
    usage: /eventcountdown <time|cancel>
    permission: qwertzcore.host.eventcountdown
  addwin:
    description: Add a win to a player's record
    usage: /addwin <player>
    permission: qwertzcore.database.addwin
  removewin:
    description: Remove a win from a player's record
    usage: /removewin <player>
    permission: qwertzcore.database.removewin
  wins:
    description: Check the number of wins a player has
    usage: /wins [player]
    permission: qwertzcore.player.checkwins
  userevive:
    description: Request to use a revive token
    usage: /userevive
    permission: qwertzcore.player.userevive
  reviveaccept:
    description: Accept a player's revive request
    usage: /reviveaccept <player>
    permission: qwertzcore.host.reviveaccept
  revivedeny:
    description: Deny a player's revive request
    usage: /revivedeny <player>
    permission: qwertzcore.host.revivedeny
  addrevive:
    description: Add a revive token to a player
    usage: /addrevive <player>
    permission: qwertzcore.host.addrevive
  removerevive:
    description: Remove a revive token from a player
    usage: /removerevive <player>
    permission: qwertzcore.host.removerevive
  revives:
    description: Check the number of revival tokens a player has
    usage: /revives [player]
    permission: qwertzcore.player.checkrevives
  discord:
    description: Get the Discord server link
    usage: /discord
    aliases: [disc, dc]
    permission: qwertzcore.player.discord
  healalive:
    description: Heal all alive players
    usage: /healalive
    permission: qwertzcore.host.healalive
  healdead:
    description: Heal all dead players
    usage: /healdead
    permission: qwertzcore.host.healdead
  mutechat:
    description: Mute the chat for all players without bypass permission
    usage: /mutechat
    permission: qwertzcore.host.mutechat
  unmutechat:
    description: Unmute the chat for all players
    usage: /unmutechat
    permission: qwertzcore.host.unmutechat
  ad:
    description: Broadcast an advertisement
    usage: /ad <platform>
    permission: qwertzcore.host.ad
  setad:
    description: Set an advertisement for a platform
    usage: /setad <platform> <message>
    permission: qwertzcore.host.setad
  message:
    description: Send a private message to a player
    usage: /message <player> <message>
    aliases: [msg, tell, w]
    permission: qwertzcore.player.message
  reply:
    description: Reply to the last player who messaged you
    usage: /reply <message>
    aliases: [r]
    permission: qwertzcore.player.message
  messagetoggle:
    description: Toggle private messages on or off
    usage: /messagetoggle
    aliases: [msgtoggle, togglemsgs]
    permission: qwertzcore.player.togglemessage
  setwarp:
    description: Set a warp at your current location
    usage: /setwarp <name>
    permission: qwertzcore.config.setwarp
  warp:
    description: Teleport to a warp
    usage: /warp <name>
    permission: qwertzcore.player.warp
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: qwertzcore.config.delwarp
  warps:
    description: List all available warps
    usage: /warps
    aliases: [listwarps]
    permission: qwertzcore.player.listwarps
  eventblock:
    description: Get a special QWERTZ Core event block
    usage: /eventblock <block> [material]
    permission: qwertzcore.host.eventblock
  createkit:
    description: Sets a kit to the player's items
    usage: /createkit <kitname>
    permission: qwertzcore.config.createkit
  kit:
    description: Gives the player/players the items in the kit
    usage: /kit <kitname> <alive|dead|all>
    permission: qwertzcore.host.kit
  delkit:
    description: Removes a kit
    usage: /delkit <kitname>
    permission: qwertzcore.config.delkit
  kits:
    description: Sends a list of kits
    usage: /kits
    permission: qwertzcore.host.kits
  invsee:
    description: View and modify another player's inventory
    usage: /invsee <player>
    permission: qwertzcore.host.invsee
  pvp:
    description: Toggle PvP in the current region or globally
    usage: /pvp [region]
    permission: qwertzcore.host.pvp
    aliases: [togglepvp]
  break:
    description: Toggle block breaking in the current region or globally
    usage: /break [region]
    permission: qwertzcore.host.break
    aliases: [togglebreak]
  flow:
    description: Toggle flowing in the current region or globally
    usage: /flow [region]
    permission: qwertzcore.host.flow
    aliases: [toggleflow]
  place:
    description: Toggle block placing in the current region or globally
    usage: /place [region]
    permission: qwertzcore.host.place
    aliases: [toggleplace]
  falldamage:
    description: Toggle block breaking in the current region or globally
    usage: /falldamage [region]
    permission: qwertzcore.host.falldamage
    aliases: [togglefalldamage]
  hunger:
    description: Toggle block placing in the current region or globally
    usage: /hunger [region]
    permission: qwertzcore.host.hunger
    aliases: [togglehunger]
  poll:
    description: Create and manage polls
    usage: /poll <duration> <question> <answer1> <answer2> [answer3] ...
    permission: qwertzcore.host.poll
  pollvote:
    description: Vote in an active poll
    usage: /pollvote <option>
    permission: qwertzcore.player.pollvote
  setspawn:
    description: Set the spawn location to the current position
    usage: /<command>
    permission: qwertzcore.host.setspawn
  setserver:
    description: Set the server
    usage: /<command> <name>
    permission: qwertzcore.host.setserver
  setevent:
    description: Set the event
    usage: /<command> <name>
    permission: qwertzcore.host.setevent
  reloadcore:
    description: Reload the core
    usage: /<command>
    permission: qwertzcore.host.reloadcore
    aliases: [core reload]
  theme:
    description: Set the theme
    usage: /<command> <theme>
    permission: qwertzcore.host.settheme
    aliases: [settheme]
  emojis:
    description: List all emojis
    usage: /<command>
    permission: qwertzcore.player.emojis
    aliases: [emotes]
  speed:
    description: Set your speed
    usage: /<command> <speed>
    permission: qwertzcore.staff.speed
permissions:
  qwertzcore.host.timer:
    description: Allows the user to start and cancel timers
    default: op
  qwertzcore.gamemode.creative:
    description: Allows the user to set their gamemode to creative
    default: op
  qwertzcore.gamemode.survival:
    description: Allows the user to set their gamemode to survival
    default: op
  qwertzcore.gamemode.spectator:
    description: Allows the user to set their gamemode to spectator
    default: op
  qwertzcore.gamemode.adventure:
    description: Allows the user to set their gamemode to adventure
    default: op
  qwertzcore.gamemode:
    description: Allows the user to set their gamemode using the general command
    default: op
  qwertzcore.host.revival:
    description: Allows the user to start revivals
    default: op
  qwertzcore.host.revive:
    description: Allows the user to revive someone
    default: op
  qwertzcore.host.unrevive:
    description: Allows the user to unrevive someone
    default: op
  qwertzcore.host.reviveall:
    description: Allows the user to revive all players
    default: op
  qwertzcore.host.unreviveall:
    description: Allows the user to unrevive all players
    default: op
  qwertzcore.host.listalive:
    description: Allows the user to list alive players
    default: op
  qwertzcore.host.listdead:
    description: Allows the user to list dead players
    default: op
  qwertzcore.host.givedead:
    description: Allows the user to give an item to all dead players
    default: op
  qwertzcore.host.givealive:
    description: Allows the user to give an item to all alive players
    default: op
  qwertzcore.host.tpalive:
    description: Allows the user to teleport all alive players to them
    default: op
  qwertzcore.host.tpdead:
    description: Allows the user to teleport all dead players to them
    default: op
  qwertzcore.host.tphere:
    description: Allows the user to teleport a player to them
    default: op
  qwertzcore.config:
    description: Allows the user to edit the QWERTZ Core config
    default: op
  qwertzcore.player.spawn:
    description: Allows the user to teleport to spawn
    default: true
  qwertzcore.host.clearalive:
    description: Allows the user to clear the inventory of all alive players
    default: op
  qwertzcore.host.cleardead:
    description: Allows the user to clear the inventory of all dead players
    default: op
  qwertzcore.host.revivelast:
    description: Allows the user to revive all players who died recently
    default: op
  qwertzcore.player.hide:
    description: Allows the player to hide specific groups for them
    default: true
  qwertzcore.host.eventcountdown:
    description: Allows the user to start the event countdown
    default: op
  qwertzcore.database.addwin:
    description: Allows the user to add a win to someone
    default: op
  qwertzcore.database.removewin:
    description: Allows the user to remove a win from someone
    default: op
  qwertzcore.player.checkwins:
    description: Allows the player to see someones wins
    default: true
  qwertzcore.player.userevive:
    description: Allows the player to use a revive token
    default: true
  qwertzcore.host.reviveaccept:
    description: Allows the player to accept revive token requests
    default: op
  qwertzcore.host.revivedeny:
    description: Allows the player to deny revive token requests
    default: op
  qwertzcore.host.addrevive:
    description: Allows the player to give someone a revive token
    default: op
  qwertzcore.host.removerevive:
    description: Allows the player to remove a revive token from someone
    default: op
  qwertzcore.player.checkrevives:
    description: Allows the player to see someones revival tokens
    default: true
  qwertzcore.player.discord:
    description: Allows the player to join the discord
    default: true
  qwertzcore.host.healalive:
    description: Allows the player to heal alive players
    default: op
  qwertzcore.host.healdead:
    description: Allows the player to heal dead players
    default: op
  qwertzcore.host.mutechat:
    description: Allows the player to mute the chat
    default: op
  qwertzcore.host.unmutechat:
    description: Allows the player to unmute the chat
    default: op
  qwertzcore.chat.bypass:
    description: Allows the player to bypass a muted chat
    default: op
  qwertzcore.host.ad:
    description: Allows the player broadcast an advertisement
    default: op
  qwertzcore.config.setad:
    description: Allows the player to set an advertisement link
    default: op
  qwertzcore.player.message:
    description: Allows the player to private message and reply to other players
    default: true
  qwertzcore.player.togglemessage:
    description: Allows the player to toggle private messages towards him on or off
    default: true
  qwertzcore.config.setwarp:
    description: Allows the player to create a warp
    default: op
  qwertzcore.config.delwarp:
    description: Allows the player to delete a warp
    default: op
  qwertzcore.player.listwarps:
    description: Allows the player list all warps
    default: true
  qwertzcore.player.warp:
    description: Allows the player to use warps
    default: true
  qwertzcore.chat.bypasstm:
    description: Allows the player to bypass the disabled vanilla commands /tm and /teammsg
    default: op
  qwertzcore.chat.bypassme:
    description: Allows the player to bypass the disabled vanilla command /me
    default: op
  qwertzcore.host.eventblock:
    description: Allows the player to create QWERTZ Core event blocks
    default: op
  qwertzcore.config.createkit:
    description: Allows the player to create kits
    default: op
  qwertzcore.config.delkit:
    description: Allows the player to delete kits
    default: op
  qwertzcore.host.kit:
    description: Allows the player to apply kits
    default: op
  qwertzcore.host.kits:
    description: Allows the player to list kits
    default: op
  qwertzcore.host.invsee:
    description: Allows the player to invsee other players
    default: op
  qwertzcore.host.vanish:
    description: Allows the player to vanish
    default: op
  qwertzcore.host.unvanish:
    description: Allows the player to unvanish
    default: op
  qwertzcore.host.pvp:
    description: Allows the player to toggle PvP
    default: op
  qwertzcore.host.break:
    description: Allows the player to toggle block breaking
    default: op
  qwertzcore.host.place:
    description: Allows the player to toggle block placing
    default: op
  qwertzcore.host.hunger:
    description: Allows the player to toggle hunger drain
    default: op
  qwertzcore.host.falldamage:
    description: Allows the player to toggle fall damage
    default: op
  qwertzcore.host.flow:
    description: Allows the player to toggle Flowing
    default: op
  qwertzcore.host.poll:
    description: Allows the player to create and manage polls
    default: op
  qwertzcore.player.pollvote:
    description: Allows the player to vote in polls
    default: true
  qwertzcore.host.setspawn:
    description: Allows the player to set the spawn
    default: op
  qwertzcore.host.setserver:
    description: Allows the player to set the server
    default: op
  qwertzcore.host.setevent:
    description: Allows the player to set the event
    default: op
  qwertzcore.host.reloadcore:
    description: Allows the player to reload the core
    default: op
  qwertzcore.host.settheme:
    description: Allows the player to change the theme
    default: op
  qwertzcore.player.emojis:
    description: Allows the player to use emojis
    default: true
  qwertzcore.staff.speed:
    description: Allows the player to set their speed
    default: op